use_frameworks!

platform :ios, '8.0'

target 'lxtCustmer_Example' do
  pod 'lxtCustmer', :path => '../'

  target 'lxtCustmer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
